### ISSUE TITLE
Incorrect cordova-plugin-carthage-support version used while install cordova-line-login-plugin@1.2.2

### ISSUE THREAD

**Issue by pipoa** [nrikiji/cordova-line-login-plugin#63]
It's a big problem when old cordova project needs to re-add(remove/add) platform. Everything becomes a mess .

to prove 
1. create a blank cordova project
$ ionic start myApp tabs
$ cd myApp/
$ ionic integrations enable cordova

2. add line-login plugin
$ ionic cordova plugin add cordova-line-login-plugin@1.2.2

3. add UseSwiftLanguageVersion to config.xml
<preference name="UseSwiftLanguageVersion" value="5" />

4. add ios platform
$ ionic cordova platform add ios

```
Use Swift language version 5
Error: Command failed: carthage update --platform iOS
Please update to the latest Carthage version: 0.36.0. You currently are on 0.33.0
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/avex/projects/ws_gassist/myApp/platforms/ios/Carthage/Checkouts/line-sdk-ios-swift/LineSDK.xcworkspace -scheme LineSDK -configuration Release -derivedDataPath /Users/avex/Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/line-sdk-ios-swift/5.7.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/kp/dt73_b753xq0qrr7ysft34h80000gn/T/line-sdk-ios-swift SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/avex/projects/ws_gassist/myApp/platforms/ios/Carthage/Checkouts/line-sdk-ios-swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/kp/dt73_b753xq0qrr7ysft34h80000gn/T/carthage-xcodebuild.FUjAfL.log

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'carthage update --platform iOS'
} Please update to the latest Carthage version: 0.36.0. You currently are on 0.33.0
Build Failed
	Task failed with exit code 65:
```

not compatible ? why?

5. cordova list plugin 
$ ionic cordova plugin ls

```
cordova-line-login-plugin 1.2.2 "Line Login"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-carthage-support 1.0.0 "Cordova Plugin Carthage Support"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
cordova-plugin-carthage-support==1.0.0 ? NEWEST ONE NOT COMPATIBLE with 1.2.2? 

6. downgrade carthage to 0.1.1 
$ ionic cordova plugin rm cordova-plugin-carthage-support --force
$ ionic cordova plugin add cordova-plugin-carthage-support@0.1.1 

7. re-add platform ios
$ ionic cordova platform rm ios
$ ionic cordova platform add ios

SUCCESS  

8. build ios 
$ ionic cordova build ios

SUCCESS

7. run device with verbose
$ ionic cordova run ios --no-native-run --verbose

SUCCESS

**Comment by nrikiji** [comment]
https://github.com/nrikiji/cordova-line-login-plugin/issues/62
I'd like to get this issue off the table when we're done here.
